config/routes.rb
Rails.application.routes.draw do
  resources :defaults

  devise_for :users
  resources :users

  root to: "defaults#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, User
    else
      can :read, User
      can :read, Client
    end
  end
end

app/models/default.rb
class Default < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create :set_default_role

  has_many :daily_report

  def full_name
    [first_name, last_name].join(' ')
  end

  def admin?
    self.role == 'admin'
  end

  def user? 
  	self.role == 'user'
  end

  private

  def set_default_role
    self.role ||= 'user'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/defaults_controller.rb
class DefaultsController < ApplicationController
  before_action :set_default, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @defaults = Default.all
    respond_with(@defaults)
  end

  def show
    respond_with(@default)
  end

  def new
    @default = Default.new
    respond_with(@default)
  end

  def edit
  end

  def create
    @default = Default.new(default_params)
    @default.save
    respond_with(@default)
  end

  def update
    @default.update(default_params)
    respond_with(@default)
  end

  def destroy
    @default.destroy
    respond_with(@default)
  end

  private
    def set_default
      @default = Default.find(params[:id])
    end

    def default_params
      params.require(:default).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:login, :email, :first_name, :last_name, :job_title, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def client_companies
    Client.pluck(:company)
  end
end

app/helpers/defaults_helper.rb
module DefaultsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/defaults/_form.html.haml
= form_for @default do |f|
  - if @default.errors.any?
    #error_explanation
      %h2= "#{pluralize(@default.errors.count, "error")} prohibited this default from being saved:"
      %ul
        - @default.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/defaults/edit.html.haml
%h1 Editing default

= render 'form'

= link_to 'Show', @default
\|
= link_to 'Back', defaults_path

app/views/defaults/index.html.haml
%h1 Listing defaults

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th
      
  %tbody
    - @defaults.each do |default|
      %tr
        %td= default.name
        %td= link_to 'Show', default
        %td= link_to 'Edit', edit_default_path(default)
        %td= link_to 'Destroy', default, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Default', new_default_path

app/views/defaults/new.html.haml
%h1 New default

= render 'form'

= link_to 'Back', defaults_path

app/views/defaults/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @default.name

= link_to 'Edit', edit_default_path(@default)
\|
= link_to 'Back', defaults_path

app/views/layouts/_footer.html.haml
%footer.footer

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default{role: 'navigation'}
  .container-fluid
    = render 'layouts/menu'

app/views/layouts/_menu.html.haml
.navbar-header
  %button.navbar-toggle{'data-target' => '#bs-example-navbar-collapse-1', 'data-toggle' => 'collapse', type: 'button'}
  %a.navbar-brand{href: root_path} Sito 92 System
#bs-example-navbar-collapse-1.collapse.navbar-collapse
  %ul.nav.navbar-nav
    %li
      %a{href: root_path} Default
    %li
      / %a{href: daily_reports_path} Reports
    %li
      %a{href: users_path} Users
    %li
      / %a{href: clients_path} Clients

  %ul.nav.navbar-nav.navbar-right
    %li.dropdown
      %a.dropdown-toggle{'data-toggle' => 'dropdown', href: '#'}
        %span
          Account
          %span.caret
      %ul.dropdown-menu{role: 'menu'}
        - if signed_in?
          - if current_user.admin?
            %li
              %a{href: edit_user_registration_path} Edit Profile
            %li
              %a{href: '#'}
          %li
            = link_to 'Log Out', destroy_user_session_path, :method => :delete
        - else
          %li
            %a{href: new_user_session_path} Log In
          %li
            %a{href: new_user_registration_path} Sign Up

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.haml
%html
  %head
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}
    %title
    = stylesheet_link_tag "application", media: "all", |
      "data-turbolinks-track" => true                  |
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    .container
      = render 'layouts/header'
    .container
      .jumbotron
        .row
          .span12
            - flash.each do |key, value|
              .form-errors
                %div
                  = content_tag(:div, value, class: "alert alert-#{key}")
            = yield
    .container
      = render 'layouts/footer'

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :job_title
    = f.text_field :job_title
  .field
    = f.label :role
    = f.text_field :role
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Email
    %th First name
    %th Last name
    %th Job title
    %th Role
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.email
      %td= user.first_name
      %td= user.last_name
      %td= user.job_title
      %td= user.role
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @user.email
%p
  %b First name:
  = @user.first_name
%p
  %b Last name:
  = @user.last_name
%p
  %b Job title:
  = @user.job_title
%p
  %b Role:
  = @user.role

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path